### ISSUE TITLE
flash error

### ISSUE THREAD

**Issue by bw1129** [conuthead/AM32-MultiRotor-ESC-firmware#1]
trying to flash IFLIGHT1_58 and it gets to 77% then hangs, giving the error "BAD OIR NO ACK FROM IF".

**Comment by Voodoobrew101** [comment]
I'm guessing but...
How are you powering the transfer? Mine seems to be best with putting 5v to the main inputs.
Also try other usb ports.
It could also Possibly be a loose connection.

**Comment by conuthead** [comment]
hi bw1129, i'll dive into it further when the ESC gets here. I am going to close this issue here since its an issue with my configurator. That will be up as a project on github soon.
